# .github/workflows/e2e.yml
name: E2E (Playwright)

on:
  workflow_dispatch:  # ← behold bare denne
  # pull_request:     # ← fjern/kommenter bort
  # push:             # ← fjern/kommenter bort

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - run: echo "E2E disabled for PRs; run manually via workflow_dispatch"

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      TEST_AUTH_BYPASS: "1"
      # Clerk React trenger kun denne – IKKE hemmelig
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_Y29uY2lzZS1tb3NxdWl0by00MS5jbGVyay5hY2NvdW50cy5kZXYk
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm run test:e2e

      - name: Upload report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
