name: RLS Verification

on:
<<<<<<< HEAD
  pull_request:
  push:
    branches: [ main ]
=======
  workflow_dispatch:   # <- kjør kun manuelt fra Actions-fanen
>>>>>>> origin/main

jobs:
  verify:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    env:
      DATABASE_URL_UNPOOLED: ${{ secrets.DATABASE_URL_UNPOOLED }}
=======
    environment: neon
    env:
      DATABASE_URL_UNPOOLED: ${{ secrets.DATABASE_URL_UNPOOLED }}

>>>>>>> origin/main
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Show psql version
        run: psql --version

<<<<<<< HEAD
=======
      - name: Sanity connect to Neon
        run: psql "$DATABASE_URL_UNPOOLED" -v ON_ERROR_STOP=1 -c "select current_user, current_database();"

>>>>>>> origin/main
      - name: Run migrations (idempotent)
        run: |
          set -euo pipefail
          for f in $(ls -1 db/migrations/*.sql | sort); do
            echo "==> Running $f"
            psql "$DATABASE_URL_UNPOOLED" -v ON_ERROR_STOP=1 -f "$f"
          done

      - name: Run final RLS verification (199)
        run: |
          set -euo pipefail
<<<<<<< HEAD
          psql "$DATABASE_URL_UNPOOLED" -v ON_ERROR_STOP=1 -a -P pager=off \
=======
          psql "$DATABASE_URL_UNPOOLED" -v ON_ERROR_STOP=1 -v "ON_ERROR_STOP=1" -v "pager=off" \
>>>>>>> origin/main
            -f db/tests/199_final_verification.sql | tee rls_199.log

      - name: Policy snapshot (current)
        run: |
<<<<<<< HEAD
          psql "$DATABASE_URL_UNPOOLED" -v ON_ERROR_STOP=1 \
            -f db/tests/198_policy_snapshot.sql > current_policy_snapshot.txt
=======
          psql "$DATABASE_URL_UNPOOLED" -Atq -f db/tests/198_policy_snapshot.sql > current_policy_snapshot.txt
>>>>>>> origin/main

      - name: Compare policy snapshot
        run: |
          set -e
<<<<<<< HEAD
          diff -u db/tests/policy_snapshot.txt current_policy_snapshot.txt
=======
          diff -u db/tests/policy_snapshot.txt current_policy_snapshot.txt || (echo "Snapshot diff"; exit 1)
>>>>>>> origin/main

      - name: Upload verification log (artifact)
        uses: actions/upload-artifact@v4
        with:
<<<<<<< HEAD
          name: rls_199_log
          path: rls_199.log

  e2e:
    needs: verify
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TEST_AUTH_BYPASS: "1"
      NODE_ENV: "test"
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install deps
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run E2E smoke
        run: npm run test:e2e


=======
          name: rls_199.log
          path: rls_199.log
>>>>>>> origin/main
