name: RLS Verification

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    # Viktig: binder til GitHub Environment "neon" (der secret ligger)
    environment: neon
    env:
      # Må være satt som Environment Secret under Settings → Environments → neon
      DATABASE_URL_UNPOOLED: ${{ secrets.DATABASE_URL_UNPOOLED }}

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Show psql version
        run: psql --version

      - name: Sanity connect to Neon
        run: |
          psql "$DATABASE_URL_UNPOOLED" -v ON_ERROR_STOP=1 -Atc "select current_user, current_database();"

      - name: Run migrations (idempotent)
        run: |
          set -euo pipefail
          for f in $(ls -1 db/migrations/*.sql | sort); do
            echo "==> Running $f"
            psql "$DATABASE_URL_UNPOOLED" -v ON_ERROR_STOP=1 -f "$f"
          done

      - name: Run final RLS verification (199)
        run: |
          set -euo pipefail
          # Kjør testen og fang både stdout og stderr i loggen (NOTICE går ofte på stderr)
          psql "$DATABASE_URL_UNPOOLED" -v ON_ERROR_STOP=1 -f db/tests/199_final_verification.sql 2>&1 | tee rls_199.log

      # ----- Inline snapshot: henter pg_policies uten egen .sql-fil -----
      - name: Policy snapshot (current)
        run: |
          set -euo pipefail
          # -A = unaligned, -t = tuples only, -q = quiet (ingen "Output format is unaligned.")
          psql "$DATABASE_URL_UNPOOLED" -v ON_ERROR_STOP=1 -Atq <<'SQL' > current_policy_snapshot.txt
          SELECT
            schemaname || '|' || tablename || '|' || policyname || '|' || cmd || '|' ||
            COALESCE(qual, '') || '|' || COALESCE(with_check, '')
          FROM pg_policies
          WHERE schemaname IN ('public','app')
          ORDER BY schemaname, tablename, policyname, cmd;
          SQL
          # Vis noen første linjer i loggen for debug
          head -n 20 current_policy_snapshot.txt || true

      - name: Compare policy snapshot
        run: |
          set -euo pipefail
          # Diff mot fasit i repo. Feiler jobben hvis det er avvik.
          diff -u db/tests/policy_snapshot.txt current_policy_snapshot.txt

      - name: Upload verification log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rls_199.log
          path: rls_199.log

      - name: Upload current policy snapshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: current_policy_snapshot.txt
          path: current_policy_snapshot.txt
